<?php
/**
 * The home page markup.
 *
 * Lives in a template part because two templates need it: front-page.php
 * when a static front page is set, and index.php when one is not. Keeping
 * one copy means they cannot drift apart.
 *
 * The world map between MAP:START and MAP:END is generated by build-map.py
 * from mandates-data.js. Re-run that script rather than editing it here.
 *
 * @package iim
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<main id="top">

  <!-- ===== Hero. Typographic by choice: the site ships before photography
       exists. To reintroduce a photograph later, restore a .hero__media
       block as the first child and the scrim rules in styles.css. ===== -->
  <section class="hero hero--type">
    <div class="hero__body">
      <p class="eyebrow">Energy &amp; Transport Advisory</p>
      <h1 class="hero__headline">
        <span class="line"><span>Let&rsquo;s build what</span></span>
        <span class="line"><span>moves the world.</span></span>
      </h1>
      <p class="hero__sub">Boutique advisory for the generation, grid and transport
        assets that economies depend on.</p>
      <div class="hero__actions">
        <a class="btn btn--lg" href="mailto:advisory@infrastructureinmotion.com">Contact a partner</a>
        <a class="more" href="<?php echo esc_url( iim_page_url( 'track-record' ) ); ?>">See the track record
          <span aria-hidden="true">&#8594;</span></a>
      </div>
    </div>
  </section>

  <!-- ===== Scale of the practice. Figures count up once in view. ===== -->
<?php get_template_part( 'template-parts/stats' ); ?>


  <!-- ===== Practice. Four rows rather than an accordion: with no images to
       reveal, hiding one sentence behind a click bought nothing, and the
       service names now sit in the heading outline. ===== -->
  <section class="section" id="practice">
    <div class="section__head reveal">
      <h2 class="section__title">What we are hired to do</h2>
    </div>

    <div class="prows">
        <div class="prow reveal" style="--i:1">
          <h3 class="prow__title">Transaction Advisory</h3>
          <p class="prow__body">Buy- and sell-side M&amp;A for operating platforms and greenfield pipelines.</p>
        </div>
        <div class="prow reveal" style="--i:2">
          <h3 class="prow__title">Project Finance</h3>
          <p class="prow__body">Debt structuring, lender negotiation and close management, start to signature.</p>
        </div>
        <div class="prow reveal" style="--i:3">
          <h3 class="prow__title">PPP &amp; Concessions</h3>
          <p class="prow__body">Risk allocation and tender design for public authorities and bidders alike.</p>
        </div>
        <div class="prow reveal" style="--i:4">
          <h3 class="prow__title">Due Diligence &amp; Models</h3>
          <p class="prow__body">Traffic, load and revenue models built to survive lender review.</p>
        </div>
    </div>
  </section>

  <!-- ===== Track record: horizontal scroll-snap carousel. =====
       TODO: replace the four project images with real photography, 4:3, min 1200x900. -->
    <!-- ===== Track record. One heading over two parts: the footprint map, then
       the selected mandates rail. The map and its key are generated by
       build-map.py from mandates-data.js between the markers below, so the
       highlighted countries can never drift from the mandate list. Re-run that
       script rather than editing anything between the markers.

       .work carries no horizontal padding of its own: the rail bleeds to the
       edge and every other child brings its own gutter, which is what
       .work__inner supplies. ===== -->
  <section class="work" id="work">
    <div class="work__inner">
      <div class="section__head reveal">
        <h2 class="section__title">Track record</h2>
        <p class="lede">Forty mandates in eleven countries, for sponsors,
          lenders and public authorities.</p>
      </div>
    </div>

    <div class="work__part">
      <div class="work__inner">
        <h3 class="work__subtitle reveal">Where we have advised</h3>
        <p class="lede reveal">Eleven countries across four continents.
          Highlighted countries carry at least one mandate below.</p>

        <?php get_template_part( 'template-parts/map' ); ?>
      </div>
    </div>

    <?php get_template_part( 'template-parts/projects' ); ?>
  </section>

  <!-- ===== Closing CTA ===== -->
  <section class="cta" id="contact">
    <h2 class="cta__title reveal">Tell us about the asset.</h2>
    <p class="cta__body reveal" style="--i:1">Send the term sheet, the tender notice, or the
      one-line question you cannot get a straight answer to. A partner replies, not a form.</p>
    <div class="cta__actions reveal" style="--i:2">
      <a class="btn btn--lg" href="mailto:advisory@infrastructureinmotion.com">Contact a partner</a>
      <a class="cta__email" href="mailto:advisory@infrastructureinmotion.com">advisory@infrastructureinmotion.com</a>
    </div>
  </section>

</main>
